name: Setup Docker Compose

on:
  push:
    branches: [ "main" ]

env:
  DATABASE_URI: ${{ secrets.DATABASE_URI }}
  PORT: ${{ secrets.PORT }}

jobs:

  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose
        run: docker-compose up -d --force-recreate --build